<?php

namespace ModulesGarden\TSSGGSModule\Packages\Samples\UI\Admin\DataTable\Tabs;


use ModulesGarden\TSSGGSModule\Components\Tab\Tab;
use ModulesGarden\TSSGGSModule\Core\Contracts\Components\AdminAreaInterface;
use ModulesGarden\TSSGGSModule\Core\Contracts\Components\AjaxOnLoadInterface;
use ModulesGarden\TSSGGSModule\Packages\Samples\UI\Admin\DataTable\QueryDataProvider\DataTable;

class TabsWidget extends \ModulesGarden\TSSGGSModule\Components\TabsWidget\TabsWidget implements AjaxOnLoadInterface, AdminAreaInterface
{
    public function loadHtml(): void
    {
        $tab = new  Tab();
        $tab->setTitle('DataTable');
        $tab->addElement(new DataTable());

        $this->addTab($tab);
    }

    public function loadData(): void
    {
        parent::loadData(); // TODO: Change the autogenerated stub

        $tab = new  Tab();
        $tab->setTitle('DataTable 2');
        $tab->addElement(new DataTable());

        $this->addTab($tab);
    }
}