<?php

//table
$_LANG['packages.product.modals.create_configurable_options.title'] = 'Create Configurable Options';

$_LANG['packages.product.services.configurable_options_group_service.autoGenerateGroupName']        = 'Configurable options for :productName product';
$_LANG['packages.product.services.configurable_options_group_service.autoGenerateGroupDescription'] = 'Auto generated by module :moduleName';
$_LANG['packages.product.services.configurable_options_group.autoGenerateGroupName']                = 'Configurable options for :productName product';
$_LANG['packages.product.services.configurable_options_group.autoGenerateGroupDescription']         = 'Auto generated by module :moduleName';
$_LANG['packages.product.forms.create_configurable_options.create_success']                         = 'Configurable options created successfully';

$_LANG['packages.product.product_configuration.form.title']                          = 'Configurable Options';
$_LANG['packages.product.product_configuration.form.button_submit']                  = 'Create Configurable Options';

$_LANG['packages.product.errors.productRequiresServer']             = 'Selected product requires server.';
$_LANG['packages.product.errors.invalidServerType']                 = 'Selected server type is invalid, please select a proper server group with the ":moduleName" servers in order to proceed.';

$_LANG['packages.product.buttons.server_configuration.button.title'] = 'Configure';
$_LANG['packages.product.modals.server_configuration.modal.title'] = 'Configure Server';
$_LANG['actions.server_config.providers.server_config_provider.create_success'] = 'Server configuration saved successfully.';
