<?php

namespace ModulesGarden\TSSGGSModule\Packages\Samples\UI\Admin\TreeView\TreeView;

use ModulesGarden\TSSGGSModule\Components\Container\Container;
use ModulesGarden\TSSGGSModule\Components\ListSimple\ListSimple;
use ModulesGarden\TSSGGSModule\Components\Text\Text;
use ModulesGarden\TSSGGSModule\Core\Components\Actions\ReloadById;
use ModulesGarden\TSSGGSModule\Core\Contracts\Components\AjaxOnActionInterface;

class TreeListItem extends \ModulesGarden\TSSGGSModule\Components\TreeListItem\TreeListItem implements AjaxOnActionInterface
{
    public function loadHtml(): void
    {
        parent::loadHtml(); // TODO: Change the autogenerated stub

        $simple = new ListSimple();
        $simple->addItem((new Text())->setText('awdawd'));
        $simple->addItem((new Text())->setText('awdawd'));
        $simple->addItem((new Text())->setText('awdawd'));

        $this->addElement($simple);
    }


    public function loadData(): void
    {
        $parentId = \ModulesGarden\TSSGGSModule\Core\Support\Facades\Request::get('formData')['item_id'];
        for ($j = 0; $j < rand(0, 5); $j++)
        {
            $subitem = new TreeListItem();
            $subitem->setTitle($j);
            $subitem->setAjaxData([
                'item_id' => $parentId . $j
            ]);
            $subitem->onClick((new ReloadById('content-widget'))->withParams(['content' => $parentId . $j]));

            $this->addElement($subitem);
        }
    }
}