<?php

namespace ModulesGarden\TSSGGSModule\Packages\Samples\UI\Admin\DataTable\Forms;

use ModulesGarden\TSSGGSModule\Components\Dropdown\Dropdown;
use ModulesGarden\TSSGGSModule\Components\Form\AbstractFormOneColumn;
use ModulesGarden\TSSGGSModule\Components\FormGroup\FormGroupHalfWidth;
use ModulesGarden\TSSGGSModule\Components\FormInputEmail\FormInputEmail;
use ModulesGarden\TSSGGSModule\Components\FormInputText\FormInputText;
use ModulesGarden\TSSGGSModule\Core\Components\Actions\Reload;
use ModulesGarden\TSSGGSModule\Core\Contracts\Components\AdminAreaInterface;
use ModulesGarden\TSSGGSModule\Core\Contracts\Components\AjaxComponentInterface;
use ModulesGarden\TSSGGSModule\Packages\Samples\UI\Admin\DataTable\Providers\UserProvider;

class UserCreate extends AbstractFormOneColumn implements AdminAreaInterface, AjaxComponentInterface
{
    protected string $provider = UserProvider::class;
    protected string $providerAction = 'create';

    public function loadHtml(): void
    {
        $this->builder->createField(FormInputText::class, 'firstname')
            ->required();
        $this->builder->createField(FormInputText::class, 'lastname')
            ->required();
        $this->builder->createField(FormInputText::class, 'address1')
            ->required();
        $this->builder->createField(FormInputText::class, 'city', false, new FormGroupHalfWidth())
            ->required();
        $this->builder->createField(FormInputText::class, 'state', false, new FormGroupHalfWidth())
            ->required();
        $this->builder->createField(FormInputEmail::class, 'email')
            ->required()
            ->email();

        $dropdown = new Dropdown();
        $dropdown->setOptions([
            'jeden' => 'xxx',
            'dwa'   => 'xxeedf'
        ]);
        $dropdown->setDefaultValueAsFirstOption();
        $dropdown->onChange(new Reload($this));
        $this->builder->addField($dropdown);
    }

    public function reload()
    {
        parent::reload(); // TODO: Change the autogenerated stub

        $this->builder->createField(FormInputText::class, uniqid('awdawdawdawd'))
            ->required();
    }
}
